-- Active: 1680138500814@@127.0.0.1@3306@1_online_ordering
DROP TABLE IF EXISTS `shopping_cart`;

DROP TABLE IF EXISTS `user_operate_logs`;

DROP TABLE IF EXISTS `Orders_detail`;

DROP TABLE IF EXISTS `Orders`;

DROP TABLE IF EXISTS `Foods_Price`;

DROP TABLE IF EXISTS `Foods`;

DROP TABLE IF EXISTS `Restaurant`;

DROP TABLE IF EXISTS `Vip`;

DROP TABLE IF EXISTS `User`;

DROP TABLE IF EXISTS `user_copy`;

SHOW TABLES;

#删除触发器
DROP TRIGGER IF EXISTS `TIGGER_INSERT_USER`;

DROP TRIGGER IF EXISTS `TIGGER_UPDATE_USER`;

DROP TRIGGER IF EXISTS `TIGGER_DELETE_USER`;

TRUNCATE User_Operate_logs;